### ISSUE TITLE
Typo in the tool's description

### ISSUE THREAD

**Issue by ricordisamoa** [toollabs/OctoData#1]
https://tools.wmflabs.org/?tool=octodata shows "Issues and pull _requsts_".
Maybe the ".description" file should be included in this repo.
![screenshot of the issue](https://cloud.githubusercontent.com/assets/4588496/3868143/b7faf00e-2025-11e4-83e5-a83df0b610fa.png)

**Comment by Rillke** [comment]
Thanks for helping me getting it right. The description is now: "Database and query service. Issues and pull requests?"

Maybe it should be included, ... but most of the content is in the public_html directory.
