### ISSUE TITLE
add toolinfo.json

### ISSUE THREAD

**Issue by ricordisamoa** [toollabs/OctoData#2]
For easier discoverability via the [Tools Directory](//tools.wmflabs.org/hay/directory/)

**Comment by Rillke** [comment]
@ricordisamoa If you like, you can just do it; you have commit access to this repo as well as access to the tool on tools.wmflabs.

**Comment by ricordisamoa** [comment]
@Rillke I just wanted to achieve consensus :)
And FWIW, I don't know whether Directory supports links in descriptions, nor what are the best keywords for the tool.

**Comment by ricordisamoa** [comment]
Fixed with https://github.com/Toollabs/info/commit/b275d64607b30e372be41b26c50d1839209fb39f?

**Comment by Rillke** [comment]
https://github.com/hay/wiki-tools/issues/22
